server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${RDS_URL}:3306/${RDS_DB}?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

logging:
  config: classpath:log4j2.xml

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expire-time: 600000
  refresh-expire-time: 1200000

